version: 0.2
phases:
  build:
    commands:
      - echo $CLOUDFORMATION_PACKAGE_S3BUCKET
      - echo $CLOUDFORMATION_PACKAGE_S3PREFIX
      - sudo apt-get install zip
      - zip -r ./prediction-api-test-a.zip *
      - aws cloudformation package
        --template-file deployment-template.yml
        --s3-bucket "$CLOUDFORMATION_PACKAGE_S3BUCKET"
        --s3-prefix "$CLOUDFORMATION_PACKAGE_S3PREFIX"
        --output-template-file cloudformation-deployment-template.yml
artifacts:
  type: zip
  files:
    - cloudformation-deployment-template.yml