AWSTemplateFormatVersion: 2010-09-09
Description: candis-prediction-api continuous delivery CFN template

Parameters:
  ArtifactBucketName:
    Type: String
    Description: Unique name to be used for the artifact S3 bucket to be created.
    AllowedPattern: "[a-z0-9\\-_.]+"
    ConstraintDescription: "Malformed S3 Bucket Name: Must only contain lower case letters, numbers, hyphens, underscores and dots."
  GitHubOwner:
    Type: String
    Default: anthnyprschka # CandisIO
    Description: GitHub repository owner
  GitHubRepo:
    Type: String
    Default: prediction-api
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: master
    Description: GitHub repository branch
  GitHubToken:
    Type: String
    Description: GitHub repository OAuth token
    NoEcho: true
  TestEnvVariable:
    Type: String
    Description: Test variable that is passed EBS environments
    # NoEcho: true

  # XXX: MongoDB-URL
  # XXX: MongoDB-username
  # XXX: MongoDB-password
  # XXX: AssetBucketName-S3Bucket

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      BucketName: !Ref ArtifactBucketName

  CodeBuildRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName:
          Fn::Sub: CodeBuildRole-${AWS::StackName}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "codebuild.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Path: /service-role/
        Policies:
          - PolicyName:
              Fn::Sub: CodeBuildTrustPolicy-${AWS::StackName}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource:
                    - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/BuildCFNProject-${AWS::StackName}
                    - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/BuildCFNProject-${AWS::StackName}:*
                - Effect: Allow
                  Action:
                    - ssm:GetParameters
                  Resource:
                    - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/CodeBuild/*"
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:GetObjectVersion
                  Resource:
                    - !GetAtt [ ArtifactBucket, Arn ]
                    - !Sub
                      - ${bucketArn}/*
                      - { bucketArn: !GetAtt [ ArtifactBucket, Arn ]}

  BuildCFNProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: BuildCFNProject-${AWS::StackName}
      Description: Build EBS deployment template and source bundle using CloudFormation.
      ServiceRole: !GetAtt [ CodeBuildRole, Arn ]
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:2.7.12
        EnvironmentVariables:
          - Name: CLOUDFORMATION_PACKAGE_S3BUCKET
            Value: !Ref ArtifactBucketName
          - Name: CLOUDFORMATION_PACKAGE_S3PREFIX
            Value: !Sub '${AWS::StackName}/'

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        # XXX Statically referenced role.
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/AWS-CodePipeline-Service
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName
      Stages:

      - Name: Source
        Actions:
        - Name: Source
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: 1
            Provider: GitHub
          Configuration:
            Owner: !Ref GitHubOwner
            Repo: !Ref GitHubRepo
            Branch: !Ref GitHubBranch
            OAuthToken: !Ref GitHubToken
          OutputArtifacts: [Name: SourceArtifact]
          RunOrder: 1

      - Name: Build
        Actions:
          - Name: CodeBuild
            InputArtifacts: [Name: SourceArtifact]
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            OutputArtifacts: [Name: CFNTemplateArtifact]
            Configuration:
              ProjectName:
                Ref: BuildCFNProject
            RunOrder: 1
      - Name: Production
        Actions:
          - Name: CreateOrReplaceChangeset
            InputArtifacts: [Name: CFNTemplateArtifact]
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CloudFormation
            Configuration:
              ActionMode: CHANGE_SET_REPLACE
              RoleArn: !GetAtt [CFNRole, Arn]
              StackName: candis-prediction-api-production-stack
              ChangeSetName: candis-prediction-api-production-changeset
              TemplatePath: CFNTemplateArtifact::cloudformation-deployment-template.yml
              Capabilities: CAPABILITY_IAM
            RunOrder: 1
          - Name:  ExecuteChangeset
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CloudFormation
            Configuration:
              ActionMode: CHANGE_SET_EXECUTE
              StackName: candis-prediction-api-production-stack
              ChangeSetName: candis-prediction-api-production-changeset
            RunOrder: 2

  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: cloudformation-beanstalk-execution-role
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:GetBucketVersioning
                - s3:PutObject
              Resource: !Sub
                - ${bucketArn}/*
                - { bucketArn: !GetAtt [ArtifactBucket, Arn] }
              Effect: Allow
            - Action:
                - elasticbeanstalk:*
                - ec2:*
                - elasticloadbalancing:*
                - autoscaling:*
                - cloudwatch:*
                - sns:*
                - cloudformation:*
                - rds:*
                - sqs:*
                - iam:PassRole
              Resource:
                - '*'
              Effect: Allow
            - Action:
                - iam:GetRole
                - iam:CreateRole
                - iam:DeleteRole
                - iam:PutRolePolicy
                - iam:AttachRolePolicy
                - iam:DeleteRolePolicy
                - iam:DetachRolePolicy
              Resource:
                - !Sub arn:aws:iam::${AWS::AccountId}:role/*
              Effect: Allow
            - Action:
                - iam:*
              Resource:
                - !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/*
              Effect: Allow

